### ISSUE TITLE
Add Release table for aws

### ISSUE THREAD

**Issue by dinesh** [datacol-io/datacol#47]
Add Dynamodb table for Release using cf

```
  DynamoReleaseTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName:
        Fn::Join:
          - "-" 
          - - !Ref AWS::StackName
            - "releases"
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
```
